<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="swathi" failures="1" tests="5" name="vtiger.Practice.RetryAnalyserPractice" time="0.023" errors="0" timestamp="2023-06-09T15:37:56 IST" skipped="4">
  <testcase classname="vtiger.Practice.RetryAnalyserPractice" name="retryAnalyser" time="0.000">
    <skipped/>
  </testcase> <!-- retryAnalyser -->
  <system-out/>
  <testcase classname="vtiger.Practice.RetryAnalyserPractice" name="retryAnalyser" time="0.019">
    <skipped/>
  </testcase> <!-- retryAnalyser -->
  <system-out/>
  <testcase classname="vtiger.Practice.RetryAnalyserPractice" name="retryAnalyser" time="0.003">
    <skipped/>
  </testcase> <!-- retryAnalyser -->
  <system-out/>
  <testcase classname="vtiger.Practice.RetryAnalyserPractice" name="retryAnalyser" time="0.001">
    <skipped/>
  </testcase> <!-- retryAnalyser -->
  <system-out/>
  <testcase classname="vtiger.Practice.RetryAnalyserPractice" name="retryAnalyser" time="0.000">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at vtiger.Practice.RetryAnalyserPractice.retryAnalyser(RetryAnalyserPractice.java:11)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- retryAnalyser -->
  <system-out/>
</testsuite> <!-- vtiger.Practice.RetryAnalyserPractice -->
